added option to create a serviceacount
EugenMayer/helm-charts pull request #18
Opened 2022-04-27 10:49 UTC by christianknell

2022-04-27 13:12 UTC, EugenMayer requested changes
Please describe your intend a bit, i have suggestions

2022-04-27 13:12 UTC, EugenMayer commented on charts/rundeck/templates/serviceaccount.yaml
> +{{- if .Values.serviceAccount.create -}}
please use 'enabled'

2022-04-27 13:12 UTC, EugenMayer commented on charts/rundeck/values.yaml
> +  create: true
this cannot be the default, please change to false

2022-04-27 13:12 UTC, EugenMayer commented on charts/rundeck/templates/serviceaccount.yaml
> +  name: {{ include "rundeck.serviceAccountName" . }}
this is the wrong variable?

2022-04-27 13:12 UTC, EugenMayer commented on charts/rundeck/templates/nginx-deployment.yaml
> +      serviceAccountName: {{ include "rundeck.serviceAccountName" . }}
wrong variable?

2022-04-28 07:01 UTC, christianknell commented
> Please describe your intend a bit, i have suggestions

Using a ServiceAccount can be useful when running a cluster that doesn't allow containers to be run as root. Then you can bind the ServiceAccount of this deployment to a new psp (or similar) to allow running as root.

2022-04-28 07:04 UTC, EugenMayer commented on charts/rundeck/templates/nginx-deployment.yaml
> +      serviceAccountName: {{ include "rundeck.serviceAccountName" . }}
@christianknell can you comment on this one? that would be great

2022-04-28 07:05 UTC, EugenMayer commented
> > Please describe your intend a bit, i have suggestions
> 
> Using a ServiceAccount can be useful when running a cluster that doesn't allow containers to be run as root. Then you can bind the ServiceAccount of this deployment to a new psp (or similar) to allow running as root.

thank you!

2022-04-28 16:55 UTC, EugenMayer approved these changes
LGTM, thank you for the contribution

2022-04-28 16:55 UTC, merged